version: "3.8"

services: 
  postgres: 
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todoDB
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis: 
    container_name: redis
    image: redis:latest
    restart: always
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "6379:6379"
  go: 
    container_name: go
    ports: 
      - "8080:8081"
    build:
      context: .
    depends_on:
      - "postgres"
      - "redis"

volumes: 
  dbdata: